version: "3.8"

services:
  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: zaki
      POSTGRES_PASSWORD: zak1
      POSTGRES_DB: solar
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./singleAxis
    container_name: flask_backend
    restart: always
    environment:
      DATABASE_URL: postgresql://$zaki:zak1@db:5432/$solar
    ports:
      - "5000:5000"
    depends_on:
      - db

volumes:
  postgres_data:
